services:
  #################
  #  databases
  #################
  db:
    image: postgres:17.4
    env_file: ./backend/.env
    restart: always
    shm_size: 128mb
    volumes:
      - workout_tracker_db_volume:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
  redis:
    image: redis:7.2-alpine
    restart: always

  #################
  #  backend
  #################
  backend:
    build: ./backend
    env_file: ./backend/.env
    # user: node
    develop:
      watch:
        - action: rebuild
          path: .
          target: /app
          ignore:
            - node_modules/
            - .git/
    depends_on:
      - db
      - redis
    ports:
      - 3000:3000

  #################
  #  frontend
  #################
  frontend:
    build: ./frontend
    ports:
      - 5173:5173
    env_file: ./frontend/.env
    develop:
      watch:
        - action: rebuild
          path: .
          target: /app
          ignore:
            - node_modules/
            - .git/

volumes:
  workout_tracker_db_volume:
